name: Merge main to gh-pages

on:
    push:
        branches:
            - master

jobs:
    merge:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: gh-pages
                  fetch-depth: 0

            - name: Merge master to gh-pages
              run: |
                  git merge --no-ff origin/master -m "Merge master into gh-pages for deploy"
                  git push origin gh-pages
